gridWorkingDir:		workingdir
gridOutputDir:		outputdir_13d_testnewlambda2
aliROOTVersion:         v5-09-23-1
aliPhysicsVersion:      vAN-20180222-1
gridDataDir:		/alice/data/2013/LHC13d
dataPattern:		/pass4/*/AliESDs.root
runPrefix:              000
runNumber:		[195783]
emcalGeometryFilename:  geometry_2015.root
emcalLocal2MasterFilename:  EMCALlocal2master.root
skimClusterMinE:        10.0